# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
sudo: false
warnings_are_errors: true

# Coveralls
r_github_packages:
  - jimhester/covr

# BiocCheck
bioc_packages:
  - BiocCheck

after_success:
  - Rscript -e 'covr::coveralls()'
  - find . -name testthat.Rout | xargs cat
  - R CMD BiocCheck --new-package --no-check-vignettes chromswitch*.tar.gz
